// src/component/ai/AiInputBar.vue
<!--
  AiInputBar：AI 输入条（DeepSeek Harness 风格一体化卡片）
  - 卡片结构：上方文本编辑区 + 下方工具行（附件 / 表情 / 引用 …… 发送）
  - 聚焦时卡片边框品牌色 + 外发光；发送键为圆形主按钮
  - 流式输出中发送键变为停止键；附件芯片显示在卡片内文本上方（可移除）
  - 粘贴智能识别：多行内容自动包成 ```代码块``` 并猜语言
  - 自动增高：最多 8 行；Enter 发送 / Shift+Enter 换行
-->
<template>
  <div class="ai-input-bar">
    <!-- 一体化输入卡片 -->
    <div class="ai-box" :class="{ 'is-focus': focused }">
      <!-- 附件芯片 -->
      <div v-if="attachments.length" class="ai-attach-row">
        <span v-for="a in attachments" :key="a.id" class="ai-attach-chip">
          <Icon name="file" :size="11" class="ai-attach-icon" />
          <span class="ai-attach-name">{{ a.name }}</span>
          <span class="ai-attach-size">{{ formatSize(a.size) }}</span>
          <button type="button" class="ai-attach-x" aria-label="移除附件" @click="removeAttachment(a.id)">
            <Icon name="times" :size="9" />
          </button>
        </span>
      </div>

      <textarea
        ref="inputRef"
        v-model="text"
        class="ai-input"
        rows="1"
        :placeholder="placeholder"
        spellcheck="false"
        @focus="focused = true"
        @blur="focused = false"
        @keydown.enter.exact.prevent="doSend"
        @input="autoGrow"
        @paste="onPaste"
      ></textarea>

      <!-- 工具行：左侧功能按钮，右侧发送/停止 -->
      <div class="ai-tools">
        <button type="button" class="ai-tool-btn" aria-label="添加附件" @click="fileInputRef?.click()">
          <Icon name="paperclip" :size="14" />
        </button>
        <button
          type="button"
          class="ai-tool-btn"
          :class="{ 'is-on': emojiOpen }"
          aria-label="表情"
          @click="toggleEmoji"
        >
          <Icon name="smile" :size="14" />
        </button>
        <button
          type="button"
          class="ai-tool-btn"
          :class="{ 'is-on': contextOpen }"
          aria-label="引用上下文"
          @click="toggleContext"
        >
          <Icon name="at-sign" :size="14" />
        </button>

        <span class="ai-tools-spacer" />

        <button
          v-if="!streaming"
          type="button"
          class="ai-send"
          aria-label="发送"
          :disabled="!canSend"
          @click="doSend"
        >
          <Icon name="arrow-up" :size="14" />
        </button>
        <button
          v-else
          type="button"
          class="ai-send is-stop"
          aria-label="停止生成"
          @click="emit('stop')"
        >
          <Icon name="stop" :size="13" />
        </button>
      </div>
    </div>

    <!-- 表情选择器 -->
    <div v-if="emojiOpen" class="ai-pop" @mousedown.stop>
      <div class="ai-pop-title">表情</div>
      <div class="ai-emoji-grid">
        <button v-for="em in emojis" :key="em" type="button" class="ai-emoji" @click="insertAtCursor(em)">
          {{ em }}
        </button>
      </div>
    </div>

    <!-- 上下文引用 -->
    <div v-if="contextOpen" class="ai-pop" @mousedown.stop>
      <div class="ai-pop-title">引用上下文</div>
      <button v-for="c in contextItems" :key="c.id" type="button" class="ai-ctx-item" @click="insertAtCursor(c.text)">
        <Icon :name="c.icon" :size="13" class="ai-ctx-icon" />
        <span class="ai-ctx-label">{{ c.label }}</span>
        <span class="ai-ctx-hint">{{ c.hint }}</span>
      </button>
    </div>

    <!-- 隐藏的附件选择 -->
    <input ref="fileInputRef" type="file" multiple class="ai-file-input" @change="onFilesPicked" />
  </div>
</template>

<script setup lang="ts">
import { computed, nextTick, onMounted, onUnmounted, ref, watch } from 'vue'
import { Icon } from '../common'

const props = withDefaults(defineProps<{
  /** 输入框占位文案（侧栏/主区可各自定制） */
  placeholder?: string
  /** 是否正在流式输出（true 时发送键变为停止键） */
  streaming?: boolean
}>(), { placeholder: '给 KazeNest 发送消息，Enter 发送，Shift+Enter 换行', streaming: false })

const emit = defineEmits<{
  send: [payload: { text: string; attachments: string[] }]
  /** 点击停止键（终止流式输出） */
  stop: []
}>()

/* =================== 输入文本 =================== */

const text = ref('')
const inputRef = ref<HTMLTextAreaElement | null>(null)
/** 聚焦态（卡片边框高亮 + 外发光） */
const focused = ref(false)

const canSend = computed(() => text.value.trim().length > 0 || attachments.value.length > 0)

/** 发送：清空输入与附件，把内容交给父级（父级调 useAiChat.send） */
function doSend() {
  if (!canSend.value) return
  const attachNames = attachments.value.map((a) => a.name)
  const payload = { text: text.value, attachments: attachNames }
  text.value = ''
  attachments.value = []
  autoGrow()
  emit('send', payload)
}

/* =================== 附件 =================== */

interface Attachment {
  id: number
  name: string
  size: number
}

let attachSeq = 0
const attachments = ref<Attachment[]>([])
const fileInputRef = ref<HTMLInputElement | null>(null)

function onFilesPicked(e: Event) {
  const input = e.target as HTMLInputElement
  const files = input.files
  if (files) {
    for (const f of Array.from(files)) {
      attachments.value.push({ id: ++attachSeq, name: f.name, size: f.size })
    }
  }
  input.value = ''
}

function removeAttachment(id: number) {
  attachments.value = attachments.value.filter((a) => a.id !== id)
}

function formatSize(bytes: number) {
  if (bytes < 1024) return `${bytes} B`
  if (bytes < 1024 * 1024) return `${(bytes / 1024).toFixed(1)} KB`
  return `${(bytes / 1024 / 1024).toFixed(1)} MB`
}

/* =================== 自动增高 =================== */

/** 最大高度：8 行 ≈ 8 × 20px 行高 */
const MAX_INPUT_H = 160

function autoGrow() {
  const ta = inputRef.value
  if (!ta) return
  ta.style.height = 'auto'
  ta.style.height = `${Math.min(ta.scrollHeight, MAX_INPUT_H)}px`
}

/* =================== 粘贴智能识别 =================== */

/** 按关键词猜编程语言（给粘贴的代码块加标记；猜不到留空） */
function detectLang(text: string): string {
  if (/^\s*(#include|int main|std::)/m.test(text)) return 'cpp'
  if (/^\s*(def |class .*:|import |print\()/m.test(text)) return 'python'
  if (/^\s*(SELECT|INSERT|UPDATE|DELETE|FROM|WHERE)/im.test(text)) return 'sql'
  if (/^\s*(const|let|var|function|=>|import|export)/m.test(text)) return 'typescript'
  if (/<!DOCTYPE|<html|<div|<style/m.test(text)) return 'html'
  if (/^\s*[\[{]/m.test(text) && /("|\w+):/.test(text)) return 'json'
  return ''
}

function onPaste(e: ClipboardEvent) {
  const paste = e.clipboardData?.getData('text/plain') ?? ''
  if (!paste) return
  e.preventDefault()
  // 已是代码块（``` 开头/结尾）或单行文本：原样插入
  const trimmed = paste.trim()
  if (/^```/.test(trimmed) && /```$/.test(trimmed)) {
    insertAtCursor(paste)
    return
  }
  if (!trimmed.includes('\n')) {
    insertAtCursor(paste)
    return
  }
  // 多行内容：自动包成代码块 + 猜语言
  const lang = detectLang(paste)
  insertAtCursor(`\`\`\`${lang}\n${trimmed}\n\`\`\``)
}

/** 在光标处插入文本并恢复焦点 */
function insertAtCursor(paste: string) {
  const ta = inputRef.value
  if (!ta) return
  const s = ta.selectionStart
  const e = ta.selectionEnd
  text.value = text.value.slice(0, s) + paste + text.value.slice(e)
  nextTick(() => {
    const pos = s + paste.length
    ta.focus()
    ta.setSelectionRange(pos, pos)
    autoGrow()
  })
}

/* =================== 表情 / 上下文引用 =================== */

const emojis = ['😊', '👍', '🎉', '🔥', '💡', '⚡', '✅', '❌', '🔍', '📝', '🎯', '🚀', '💻', '🐛', '📌', '📚']
const emojiOpen = ref(false)
const contextOpen = ref(false)

const contextItems = [
  { id: 'file',      label: '当前文件',   icon: 'file',      text: '@当前文件: ', hint: '插入当前打开的文件' },
  { id: 'selection', label: '选中代码',   icon: 'terminal',  text: '@选中代码: ', hint: '插入编辑器选中片段' },
  { id: 'workspace', label: '工作区',     icon: 'workspace', text: '@工作区: ',   hint: '插入工作区信息' },
]

const inputBarRef = ref<HTMLElement | null>(null)

function toggleEmoji() {
  emojiOpen.value = !emojiOpen.value
  contextOpen.value = false
}

function toggleContext() {
  contextOpen.value = !contextOpen.value
  emojiOpen.value = false
}

/** 点击输入框以外：关闭弹层 */
function onClickOutside(e: MouseEvent) {
  if (!emojiOpen.value && !contextOpen.value) return
  if (inputBarRef.value?.contains(e.target as Node)) return
  emojiOpen.value = false
  contextOpen.value = false
}

onMounted(() => document.addEventListener('mousedown', onClickOutside))
onUnmounted(() => document.removeEventListener('mousedown', onClickOutside))

/** 父级切换会话/新建后清空输入（父级 watch chat.activeSessionId 后调用） */
watch(() => props.placeholder, () => {
  text.value = ''
  attachments.value = []
  autoGrow()
})
</script>

<style scoped>
.ai-input-bar {
  position: relative;
  padding: 10px 12px;
  flex-shrink: 0;
}

/* ==================== 一体化输入卡片 ==================== */
.ai-box {
  display: flex;
  flex-direction: column;
  gap: 8px;
  padding: 12px 14px 8px;
  border: 1px solid var(--sb-border);
  border-radius: var(--kn-radius-xl);
  background: var(--kn-bg-elev);
  transition: border-color var(--kn-dur-fast), box-shadow var(--kn-dur-fast);
}
.ai-box.is-focus {
  border-color: color-mix(in srgb, var(--kn-brand-500) 55%, transparent);
  box-shadow: var(--kn-shadow-focus);
}

/* 隐藏的 file input（由回形针按钮触发） */
.ai-file-input {
  display: none;
}

/* 附件芯片 */
.ai-attach-row {
  display: flex;
  flex-wrap: wrap;
  gap: 4px;
}
.ai-attach-chip {
  display: inline-flex;
  align-items: center;
  gap: 4px;
  max-width: 100%;
  height: 20px;
  padding: 0 6px;
  border: 1px solid color-mix(in srgb, var(--kn-brand-500) 30%, transparent);
  border-radius: var(--kn-radius-pill);
  background: color-mix(in srgb, var(--kn-brand-500) 10%, transparent);
  color: var(--sb-fg);
  font-size: var(--kn-text-xs);
}
.ai-attach-icon {
  color: var(--kn-brand-500);
  flex-shrink: 0;
}
.ai-attach-name {
  overflow: hidden;
  text-overflow: ellipsis;
  white-space: nowrap;
}
.ai-attach-size {
  font-size: 10px;
  opacity: 0.5;
  flex-shrink: 0;
}
.ai-attach-x {
  display: inline-flex;
  align-items: center;
  justify-content: center;
  width: 14px;
  height: 14px;
  padding: 0;
  border: 0;
  border-radius: 50%;
  background: transparent;
  color: var(--sb-fg-muted);
  cursor: pointer;
  flex-shrink: 0;
}
.ai-attach-x:hover {
  background: var(--sb-hover);
  color: var(--sb-fg);
}

/* 文本编辑区（无边框，融入卡片） */
.ai-input {
  width: 100%;
  min-height: 22px;
  max-height: 160px;
  padding: 0;
  border: 0;
  outline: 0;
  background: transparent;
  color: var(--sb-fg);
  font: inherit;
  font-size: var(--kn-text-sm);
  line-height: 1.55;
  resize: none;
  box-sizing: border-box;
  overflow-y: auto;
}
.ai-input::placeholder {
  color: var(--kn-fg-subtle);
}

/* 工具行：左功能按钮 + 右发送 */
.ai-tools {
  display: flex;
  align-items: center;
  gap: 2px;
}
.ai-tools-spacer {
  flex: 1;
}
.ai-tool-btn {
  display: inline-flex;
  align-items: center;
  justify-content: center;
  width: 28px;
  height: 28px;
  border: 0;
  border-radius: var(--kn-radius-md);
  background: transparent;
  color: var(--sb-fg-muted);
  cursor: pointer;
  transition: background var(--kn-dur-fast), color var(--kn-dur-fast);
}
.ai-tool-btn:hover {
  background: var(--sb-hover);
  color: var(--sb-fg);
}
.ai-tool-btn.is-on {
  background: color-mix(in srgb, var(--kn-brand-500) 18%, transparent);
  color: var(--kn-brand-500);
}

/* 发送键：圆形主按钮（流式中变停止） */
.ai-send {
  display: inline-flex;
  align-items: center;
  justify-content: center;
  width: 30px;
  height: 30px;
  border: 0;
  border-radius: 50%;
  background: linear-gradient(135deg, var(--kn-brand-500), var(--kn-magenta-500));
  color: #fff;
  cursor: pointer;
  flex-shrink: 0;
  transition: filter var(--kn-dur-fast), transform var(--kn-dur-fast), opacity var(--kn-dur-fast);
}
.ai-send:hover:not(:disabled) {
  filter: brightness(1.1);
  transform: translateY(-1px);
}
.ai-send:disabled {
  opacity: 0.35;
  cursor: default;
}
.ai-send.is-stop {
  background: var(--kn-fg-muted);
}

/* ==================== 弹层：表情 / 上下文引用 ==================== */
.ai-pop {
  position: absolute;
  bottom: calc(100% + 2px);
  left: 12px;
  z-index: 30;
  display: flex;
  flex-direction: column;
  gap: 4px;
  min-width: 200px;
  padding: 8px;
  background: var(--kn-bg-elev);
  border: 1px solid var(--kn-border-strong);
  border-radius: var(--kn-radius-lg);
  box-shadow: var(--kn-shadow-lg);
  animation: ai-pop-in var(--kn-dur-base) var(--kn-ease-out);
}
@keyframes ai-pop-in {
  from { opacity: 0; transform: translateY(4px); }
  to   { opacity: 1; transform: translateY(0); }
}
.ai-pop-title {
  padding: 0 2px 4px;
  font-size: var(--kn-text-xs);
  font-weight: 600;
  color: var(--sb-fg-muted);
  border-bottom: 1px solid var(--kn-border);
}

/* 表情网格 */
.ai-emoji-grid {
  display: grid;
  grid-template-columns: repeat(8, 1fr);
  gap: 2px;
}
.ai-emoji {
  display: inline-flex;
  align-items: center;
  justify-content: center;
  height: 24px;
  padding: 0;
  border: 0;
  border-radius: var(--kn-radius-sm);
  background: transparent;
  font-size: var(--kn-text-lg);
  cursor: pointer;
  transition: background var(--kn-dur-fast);
}
.ai-emoji:hover {
  background: var(--sb-hover);
}

/* 上下文引用项 */
.ai-ctx-item {
  display: flex;
  align-items: center;
  gap: 6px;
  padding: 6px 6px;
  border: 0;
  border-radius: var(--kn-radius-sm);
  background: transparent;
  color: var(--sb-fg);
  font: inherit;
  font-size: var(--kn-text-sm);
  cursor: pointer;
  text-align: left;
  transition: background var(--kn-dur-fast);
}
.ai-ctx-item:hover {
  background: var(--sb-hover);
}
.ai-ctx-icon {
  color: var(--kn-brand-500);
  flex-shrink: 0;
}
.ai-ctx-label {
  flex-shrink: 0;
}
.ai-ctx-hint {
  flex: 1;
  overflow: hidden;
  text-overflow: ellipsis;
  white-space: nowrap;
  font-size: var(--kn-text-xs);
  color: var(--sb-fg-muted);
}
</style>

// src/component/ai/AiInputBar.tsx
/**
 * AiInputBar：AI 输入条（React 版，一体化卡片）
 * - 卡片结构：附件芯片 + 文本编辑区 + 工具行（附件/表情/引用 → 发送/停止）
 * - 聚焦高亮、自动增高（最多 8 行）、Enter 发送 / Shift+Enter 换行
 * - 粘贴智能识别：多行内容自动包成 ```代码块``` 并猜语言
 * - 流式输出中发送键变为停止键
 */
import { useEffect, useRef, useState } from 'react'
import { Icon } from '@/component/common/Icon'
import './ai.css'

interface Attachment {
  id: number
  name: string
  size: number
}

export interface AiInputBarProps {
  placeholder?: string
  streaming?: boolean
  onSend: (payload: { text: string; attachments: string[] }) => void
  onStop: () => void
}

const EMOJIS = ['😊', '👍', '🎉', '🔥', '💡', '⚡', '✅', '❌', '🔍', '📝', '🎯', '🚀', '💻', '🐛', '📌', '📚']

const CONTEXT_ITEMS = [
  { id: 'file', label: '当前文件', icon: 'file', text: '@当前文件: ', hint: '插入当前打开的文件' },
  { id: 'selection', label: '选中代码', icon: 'terminal', text: '@选中代码: ', hint: '插入编辑器选中片段' },
  { id: 'workspace', label: '工作区', icon: 'workspace', text: '@工作区: ', hint: '插入工作区信息' },
]

const MAX_INPUT_H = 160

function formatSize(bytes: number) {
  if (bytes < 1024) return `${bytes} B`
  if (bytes < 1024 * 1024) return `${(bytes / 1024).toFixed(1)} KB`
  return `${(bytes / 1024 / 1024).toFixed(1)} MB`
}

/** 按关键词猜编程语言（给粘贴的代码块加标记） */
function detectLang(text: string): string {
  if (/^\s*(#include|int main|std::)/m.test(text)) return 'cpp'
  if (/^\s*(def |class .*:|import |print\()/m.test(text)) return 'python'
  if (/^\s*(SELECT|INSERT|UPDATE|DELETE|FROM|WHERE)/im.test(text)) return 'sql'
  if (/^\s*(const|let|var|function|=>|import|export)/m.test(text)) return 'typescript'
  if (/<!DOCTYPE|<html|<div|<style/m.test(text)) return 'html'
  if (/^\s*[\[{]/m.test(text) && /("|\w+):/.test(text)) return 'json'
  return ''
}

export function AiInputBar({
  placeholder = '给 KazeNest 发送消息，Enter 发送，Shift+Enter 换行',
  streaming = false,
  onSend,
  onStop,
}: AiInputBarProps) {
  const [text, setText] = useState('')
  const [focused, setFocused] = useState(false)
  const [attachments, setAttachments] = useState<Attachment[]>([])
  const [emojiOpen, setEmojiOpen] = useState(false)
  const [contextOpen, setContextOpen] = useState(false)
  const attachSeq = useRef(0)
  const inputRef = useRef<HTMLTextAreaElement>(null)
  const fileInputRef = useRef<HTMLInputElement>(null)
  const barRef = useRef<HTMLDivElement>(null)

  const canSend = text.trim().length > 0 || attachments.length > 0

  const autoGrow = () => {
    const ta = inputRef.current
    if (!ta) return
    ta.style.height = 'auto'
    ta.style.height = `${Math.min(ta.scrollHeight, MAX_INPUT_H)}px`
  }

  const insertAtCursor = (paste: string) => {
    const ta = inputRef.current
    if (!ta) return
    const s = ta.selectionStart
    const e = ta.selectionEnd
    setText((prev) => prev.slice(0, s) + paste + prev.slice(e))
    window.setTimeout(() => {
      const pos = s + paste.length
      ta.focus()
      ta.setSelectionRange(pos, pos)
      autoGrow()
    }, 0)
  }

  const doSend = () => {
    if (!canSend) return
    const payload = { text, attachments: attachments.map((a) => a.name) }
    setText('')
    setAttachments([])
    window.setTimeout(autoGrow, 0)
    onSend(payload)
  }

  /* 点击输入条以外：关闭弹层 */
  useEffect(() => {
    if (!emojiOpen && !contextOpen) return
    const onDown = (e: MouseEvent) => {
      if (barRef.current?.contains(e.target as Node)) return
      setEmojiOpen(false)
      setContextOpen(false)
    }
    document.addEventListener('mousedown', onDown)
    return () => document.removeEventListener('mousedown', onDown)
  }, [emojiOpen, contextOpen])

  const onPaste = (e: React.ClipboardEvent<HTMLTextAreaElement>) => {
    const paste = e.clipboardData.getData('text/plain')
    if (!paste) return
    const trimmed = paste.trim()
    if (/^```/.test(trimmed) && /```$/.test(trimmed)) {
      e.preventDefault()
      insertAtCursor(paste)
      return
    }
    if (!trimmed.includes('\n')) return
    e.preventDefault()
    const lang = detectLang(paste)
    insertAtCursor(`\`\`\`${lang}\n${trimmed}\n\`\`\``)
  }

  return (
    <div ref={barRef} className="ai-input-bar">
      <div className={`ai-box${focused ? ' is-focus' : ''}`}>
        {attachments.length > 0 && (
          <div className="ai-attach-row">
            {attachments.map((a) => (
              <span key={a.id} className="ai-attach-chip">
                <Icon name="file" size={11} className="ai-attach-icon" />
                <span className="ai-attach-name">{a.name}</span>
                <span className="ai-attach-size">{formatSize(a.size)}</span>
                <button
                  type="button"
                  className="ai-attach-x"
                  aria-label="移除附件"
                  onClick={() => setAttachments((prev) => prev.filter((x) => x.id !== a.id))}
                >
                  <Icon name="times" size={9} />
                </button>
              </span>
            ))}
          </div>
        )}

        <textarea
          ref={inputRef}
          className="ai-input"
          rows={1}
          placeholder={placeholder}
          spellCheck={false}
          value={text}
          onFocus={() => setFocused(true)}
          onBlur={() => setFocused(false)}
          onChange={(e) => {
            setText(e.target.value)
            autoGrow()
          }}
          onInput={autoGrow}
          onPaste={onPaste}
          onKeyDown={(e) => {
            if (e.key === 'Enter' && !e.shiftKey && !e.nativeEvent.isComposing) {
              e.preventDefault()
              doSend()
            }
          }}
        />

        <div className="ai-tools">
          <button type="button" className="ai-tool-btn" aria-label="添加附件" onClick={() => fileInputRef.current?.click()}>
            <Icon name="paperclip" size={14} />
          </button>
          <button
            type="button"
            className={`ai-tool-btn${emojiOpen ? ' is-on' : ''}`}
            aria-label="表情"
            onClick={() => {
              setEmojiOpen((v) => !v)
              setContextOpen(false)
            }}
          >
            <Icon name="smile" size={14} />
          </button>
          <button
            type="button"
            className={`ai-tool-btn${contextOpen ? ' is-on' : ''}`}
            aria-label="引用上下文"
            onClick={() => {
              setContextOpen((v) => !v)
              setEmojiOpen(false)
            }}
          >
            <Icon name="at-sign" size={14} />
          </button>

          <span className="ai-tools-spacer" />

          {!streaming ? (
            <button type="button" className="ai-send" aria-label="发送" disabled={!canSend} onClick={doSend}>
              <Icon name="arrow-up" size={14} />
            </button>
          ) : (
            <button type="button" className="ai-send is-stop" aria-label="停止生成" onClick={onStop}>
              <Icon name="stop" size={13} />
            </button>
          )}
        </div>
      </div>

      {emojiOpen && (
        <div className="ai-pop" onMouseDown={(e) => e.stopPropagation()}>
          <div className="ai-pop-title">表情</div>
          <div className="ai-emoji-grid">
            {EMOJIS.map((em) => (
              <button key={em} type="button" className="ai-emoji" onClick={() => insertAtCursor(em)}>
                {em}
              </button>
            ))}
          </div>
        </div>
      )}

      {contextOpen && (
        <div className="ai-pop" onMouseDown={(e) => e.stopPropagation()}>
          <div className="ai-pop-title">引用上下文</div>
          {CONTEXT_ITEMS.map((c) => (
            <button key={c.id} type="button" className="ai-ctx-item" onClick={() => insertAtCursor(c.text)}>
              <Icon name={c.icon} size={13} className="ai-ctx-icon" />
              <span className="ai-ctx-label">{c.label}</span>
              <span className="ai-ctx-hint">{c.hint}</span>
            </button>
          ))}
        </div>
      )}

      <input
        ref={fileInputRef}
        type="file"
        multiple
        className="ai-file-input"
        onChange={(e) => {
          const files = e.target.files
          if (files) {
            const next: Attachment[] = []
            for (const f of Array.from(files)) {
              next.push({ id: ++attachSeq.current, name: f.name, size: f.size })
            }
            setAttachments((prev) => [...prev, ...next])
          }
          e.target.value = ''
        }}
      />
    </div>
  )
}
