// src/pages/Editor.tsx
/**
 * Editor：编辑器页（React 版）
 * - 标签页（EditorTabs）→ 代码区（CodeView）→ 状态栏（StatusBar）
 * - 文件数据来自 data/editorFiles（后续接 Tauri 文件系统）
 * - 编辑联动：CodeView 变更 → 更新内容 + 标记未保存；Ctrl+S 清除标记
 * - 会话持久化：标签 / 内容 / 未保存标记（useAppSession）
 */
import { useCallback, useEffect, useState } from 'react'
import { EditorTabs } from '@/component/editor/EditorTabs'
import { CodeView } from '@/component/editor/CodeView'
import { StatusBar } from '@/component/editor/StatusBar'
import { editorFiles } from '@/data/editorFiles'
import type { EditorFile } from '@/data/editorFiles'
import { addRecentFile } from '@/utils'
import { useAppSession } from '@/hooks/useAppSession'
import '@/component/editor/tokens.css'
import '@/component/editor/editor.css'

/** 无标签时的兜底空文件（CodeView 有"空文件"空态） */
const EMPTY_FILE: EditorFile = {
  id: '',
  name: '未打开文件',
  language: '',
  icon: 'file',
  content: '',
}

export function Editor() {
  const [openFiles, setOpenFiles] = useState<EditorFile[]>(() => [...editorFiles])
  const [activeFileId, setActiveFileId] = useState(editorFiles[0]?.id ?? '')
  const [cursor, setCursor] = useState({ line: 1, col: 1, selected: 0 })
  const [sessionReady, setSessionReady] = useState(false)

  const { restore, update } = useAppSession()

  /* ==================== 会话恢复 ==================== */

  useEffect(() => {
    let cancelled = false
    void restore().then((saved) => {
      if (cancelled) return
      const ed = saved?.editor
      if (ed?.initialized) {
        const byId = new Map(editorFiles.map((f) => [f.id, f]))
        const files = ed.openFileIds
          .map((id) => byId.get(id))
          .filter((f): f is EditorFile => Boolean(f))
          .map((f) => ({
            ...f,
            content: ed.contents[f.id] ?? f.content,
            modified: ed.modifiedIds.includes(f.id),
          }))
        setOpenFiles(files)
        setActiveFileId(
          files.some((f) => f.id === ed.activeFileId) ? ed.activeFileId : (files[0]?.id ?? '')
        )
      }
      setSessionReady(true)
    })
    return () => {
      cancelled = true
    }
  }, [restore])

  /* 标签 / 内容 / 未保存标记变化 → 写回快照防抖落盘 */
  useEffect(() => {
    if (!sessionReady) return
    update((s) => {
      s.editor = {
        initialized: true,
        openFileIds: openFiles.map((f) => f.id),
        activeFileId,
        contents: Object.fromEntries(openFiles.map((f) => [f.id, f.content])),
        modifiedIds: openFiles.filter((f) => f.modified).map((f) => f.id),
      }
    })
  }, [openFiles, activeFileId, sessionReady, update])

  /* ==================== 编辑联动 ==================== */

  const activeFile =
    openFiles.find((f) => f.id === activeFileId) ?? openFiles[0] ?? EMPTY_FILE

  const onContentUpdate = useCallback(
    (content: string) => {
      setOpenFiles((prev) =>
        prev.map((f) =>
          f.id === activeFile.id && f.content !== content ? { ...f, content, modified: true } : f
        )
      )
    },
    [activeFile.id]
  )

  const onCursor = useCallback((pos: { line: number; col: number; selected: number }) => {
    setCursor(pos)
  }, [])

  /** Ctrl+S：保存当前文件（演示版仅清除未保存标记） */
  const onSave = useCallback(() => {
    setOpenFiles((prev) => prev.map((f) => (f.id === activeFile.id && f.modified ? { ...f, modified: false } : f)))
  }, [activeFile.id])

  useEffect(() => {
    const onKeydown = (e: KeyboardEvent) => {
      const mod = e.metaKey || e.ctrlKey
      if (mod && e.key.toLowerCase() === 's') {
        e.preventDefault()
        onSave()
      }
    }
    window.addEventListener('keydown', onKeydown)
    return () => window.removeEventListener('keydown', onKeydown)
  }, [onSave])

  /* ==================== 标签操作 ==================== */

  const onTabSelect = (id: string) => {
    if (id === activeFileId) return
    setActiveFileId(id)
    const f = openFiles.find((x) => x.id === id)
    if (f) void addRecentFile({ name: f.id, icon: f.icon, color: f.color, timestamp: Date.now() })
  }

  const onCloseTab = (id: string) => {
    const idx = openFiles.findIndex((f) => f.id === id)
    if (idx === -1) return
    const next = openFiles.slice()
    const closedActive = next[idx].id === activeFileId
    next.splice(idx, 1)
    if (closedActive) {
      const neighbor = next[idx] ?? next[idx - 1]
      setActiveFileId(neighbor?.id ?? '')
    }
    setOpenFiles(next)
  }

  const onReorder = ({ from, to }: { from: number; to: number }) => {
    setOpenFiles((prev) => {
      const arr = prev.slice()
      const [item] = arr.splice(from, 1)
      arr.splice(to, 0, item)
      return arr
    })
  }

  const onCloseOthers = () => {
    if (activeFileId) setOpenFiles((prev) => prev.filter((f) => f.id === activeFileId))
  }

  const onCloseAll = () => {
    setOpenFiles([])
    setActiveFileId('')
  }

  const onCloseSaved = () => {
    setOpenFiles((prev) => {
      const next = prev.filter((f) => f.modified || f.id === activeFileId)
      if (!next.some((f) => f.id === activeFileId)) setActiveFileId(next[0]?.id ?? '')
      return next
    })
  }

  return (
    <div className="editor-page">
      <EditorTabs
        files={openFiles}
        activeId={activeFileId}
        onSelect={onTabSelect}
        onClose={onCloseTab}
        onCloseOthers={onCloseOthers}
        onCloseAll={onCloseAll}
        onCloseSaved={onCloseSaved}
        onReorder={onReorder}
      />

      <CodeView file={activeFile} onUpdate={onContentUpdate} onCursor={onCursor} />

      <StatusBar file={activeFile} line={cursor.line} col={cursor.col} selected={cursor.selected} />
    </div>
  )
}

// src/pages/Editor.vue
<!--
  Editor：编辑器页
  - 标签页（EditorTabs）→ 代码区（CodeView）→ 状态栏（StatusBar）
  - 文件数据来自 data/editorFiles.ts（后续接 Tauri 文件系统）
  - 编辑联动：CodeView 变更 → 更新内容 + 标记未保存；Ctrl+S 清除标记
  - 关闭标签：自动切换到相邻标签；关闭全部后进入空文件态
-->
<template>
  <div class="editor-page">
    <EditorTabs
      :files="openFiles"
      :model-value="activeFileId"
      @update:model-value="onTabSelect"
      @close="onCloseTab"
      @close-others="onCloseOthers"
      @close-all="onCloseAll"
      @close-saved="onCloseSaved"
      @reorder="onReorder"
    />

    <CodeView :file="activeFile" @update="onContentUpdate" @cursor="onCursor" />

    <StatusBar
      :file="activeFile"
      :line="cursor.line"
      :col="cursor.col"
      :selected="cursor.selected"
    />
  </div>
</template>

<script setup lang="ts">
import { computed, onBeforeUnmount, onMounted, ref, watch } from 'vue'
import { EditorTabs, CodeView, StatusBar } from '../component/editor'
import { editorFiles } from '../data/editorFiles'
import type { EditorFile } from '../data/editorFiles'
import { addRecentFile } from '../utils'
import { useAppSession } from '../composables'

/** 打开的标签（初始 = 全部示例文件；可关闭）
 * 调节：想让编辑器初始打开别的文件，改 data/editorFiles.ts，
 * 这里会自动跟随；初始活动标签 = 数组第一项。 */
const openFiles = ref<EditorFile[]>([...editorFiles])
const activeFileId = ref(editorFiles[0]?.id ?? '')

/* =================== 会话持久化（标签/内容/未保存标记） =================== */

const { session, restore, save, flush } = useAppSession()

/** 把当前编辑器状态写回共享快照 */
function syncSession() {
  const s = session.value
  if (!s) return
  s.editor = {
    initialized: true,
    openFileIds: openFiles.value.map((f) => f.id),
    activeFileId: activeFileId.value,
    contents: Object.fromEntries(openFiles.value.map((f) => [f.id, f.content])),
    modifiedIds: openFiles.value.filter((f) => f.modified).map((f) => f.id),
  }
}

/** 标签/内容/未保存标记任一变化 → 写回快照并防抖落盘（deep 捕获 f.content/f.modified 原地改） */
watch([openFiles, activeFileId], () => {
  syncSession()
  save()
}, { deep: true })

/** 启动恢复：有快照用快照，否则默认全部示例文件并初始化快照 */
async function restoreEditor() {
  const s = await restore()
  if (!s) return
  const ed = s.editor
  if (ed?.initialized) {
    const byId = new Map(editorFiles.map((f) => [f.id, f]))
    openFiles.value = ed.openFileIds
      .map((id) => byId.get(id))
      .filter((f): f is EditorFile => Boolean(f))
      .map((f) => ({
        ...f,
        content: ed.contents[f.id] ?? f.content,
        modified: ed.modifiedIds.includes(f.id),
      }))
    activeFileId.value = openFiles.value.some((f) => f.id === ed.activeFileId)
      ? ed.activeFileId
      : (openFiles.value[0]?.id ?? '')
  } else {
    // 首次运行：默认打开全部示例文件（与无持久化时代行为一致）
    openFiles.value = [...editorFiles]
    activeFileId.value = editorFiles[0]?.id ?? ''
    syncSession()
  }
}

/** 无标签时的兜底空文件（CodeView 已有"空文件"空态展示） */
const EMPTY_FILE: EditorFile = {
  id: '',
  name: '未打开文件',
  language: '',
  icon: 'file',
  content: '',
}

const activeFile = computed(
  () => openFiles.value.find((f) => f.id === activeFileId.value) ?? openFiles.value[0] ?? EMPTY_FILE
)

const cursor = ref({ line: 1, col: 1, selected: 0 })

function onCursor(pos: { line: number; col: number; selected: number }) {
  cursor.value = pos
}

/** 代码内容变更：更新文件内容并标记未保存 */
function onContentUpdate(content: string) {
  const f = activeFile.value
  if (!f || f.content === content) return
  f.content = content
  f.modified = true
}

/** Ctrl+S：保存当前文件（演示版仅清除未保存标记） */
function onSave() {
  const f = activeFile.value
  if (!f || !f.modified) return
  f.modified = false
}

/* =================== 标签操作 =================== */

/** 用户点击标签切换：切到某文件即记为"最近打开"（首次初始激活不算） */
function onTabSelect(id: string) {
  if (id === activeFileId.value) return
  activeFileId.value = id
  const f = openFiles.value.find((x) => x.id === id)
  if (f) addRecentFile({ name: f.id, icon: f.icon, color: f.color, timestamp: Date.now() })
}

function onCloseTab(id: string) {
  const idx = openFiles.value.findIndex((f) => f.id === id)
  if (idx === -1) return
  // 关闭的是当前活动标签 → 切换到相邻标签
  if (openFiles.value[idx].id === activeFileId.value) {
    const next = openFiles.value[idx + 1] ?? openFiles.value[idx - 1]
    activeFileId.value = next?.id ?? ''
  }
  openFiles.value.splice(idx, 1)
}

/** 拖拽排序标签：把 from 移到 to */
function onReorder({ from, to }: { from: number; to: number }) {
  const arr = openFiles.value.slice()
  const [item] = arr.splice(from, 1)
  arr.splice(to, 0, item)
  openFiles.value = arr
}

/** ⋯ 菜单：关闭其他标签 */
function onCloseOthers() {
  if (activeFileId.value) {
    openFiles.value = openFiles.value.filter((f) => f.id === activeFileId.value)
  }
}

/** ⋯ 菜单：关闭全部标签（进入空文件态） */
function onCloseAll() {
  openFiles.value = []
  activeFileId.value = ''
}

/** ⋯ 菜单：关闭所有已保存标签（未保存的保留） */
function onCloseSaved() {
  const activeId = activeFileId.value
  openFiles.value = openFiles.value.filter((f) => f.modified || f.id === activeId)
  if (!openFiles.value.some((f) => f.id === activeFileId.value)) {
    activeFileId.value = openFiles.value[0]?.id ?? ''
  }
}

/* =================== 全局快捷键 & 会话恢复 =================== */

onMounted(async () => {
  window.addEventListener('keydown', onGlobalKeydown)
  /* 恢复上次会话（标签/内容/未保存标记；KeepAlive 下只在首次挂载时执行） */
  await restoreEditor()
  /* 关闭窗口前立即落盘 */
  window.addEventListener('beforeunload', flush)
})
onBeforeUnmount(() => {
  window.removeEventListener('keydown', onGlobalKeydown)
  window.removeEventListener('beforeunload', flush)
})

function onGlobalKeydown(e: KeyboardEvent) {
  const mod = e.metaKey || e.ctrlKey
  if (mod && e.key.toLowerCase() === 's') {
    e.preventDefault()
    onSave()
  }
}
</script>

<style scoped>
/* VS Code 风格：无圆角、无边框、无外框阴影，通栏铺满 */
.editor-page {
  display: flex;
  flex-direction: column;
  height: 100%;
  min-height: 0;
  overflow: hidden;
  background: var(--ed-bg);
  animation: editor-fade var(--kn-dur-slow) var(--kn-ease-out);
}
@keyframes editor-fade {
  from { opacity: 0; transform: translateY(6px); }
  to   { opacity: 1; transform: translateY(0); }
}
</style>
