// src/component/sidebar/views/FilesSidebar.tsx
/**
 * FilesSidebar：文件管理侧栏（React 版，与页面目录同步）
 * - 「文件夹」模式目录树与页面共享同一份状态（useFileManager）
 * - 空间入口：文件夹 / 资料空间 / 私有空间
 * - 未打开文件夹时显示"打开文件夹…"入口
 */
import { useMemo, useState } from 'react'
import { SidebarSection, SidebarRow } from './SidebarRow'
import { SideBarTree } from '../SideBarTree'
import type { TreeItem } from '../types'
import { useFileManager } from '@/hooks/useFileManager'
import type { FolderNode } from '@/component/files/types'
import './view-sidebar.css'

function toTreeItems(nodes: FolderNode[]): TreeItem[] {
  return nodes.map((n) => ({
    id: n.id,
    label: n.name,
    icon: n.children?.length ? undefined : 'folder',
    children: n.children?.length ? toTreeItems(n.children) : undefined,
  }))
}

export function FilesSidebar() {
  const fm = useFileManager()
  const [collapsed, setCollapsed] = useState<Set<string>>(new Set())

  const folderItems = useMemo(() => toTreeItems(fm.folders), [fm.folders, fm])

  const pickAll = () => {
    fm.setSpace('folder')
    fm.selectFolder('')
  }

  const onOpenFolder = () => {
    fm.setSpace('folder')
    fm.openFolder()
  }

  const onNode = (item: TreeItem) => {
    fm.setSpace('folder')
    fm.selectFolder(item.id)
  }

  return (
    <div className="vs">
      <SidebarSection title="目录" icon="folder">
        {fm.folderOpened ? (
          <>
            <SidebarRow
              icon="th-large"
              selected={fm.space === 'folder' && !fm.activeFolderId}
              onClick={pickAll}
              meta={<span className="vs-meta">{fm.folderFiles.length}</span>}
            >
              全部文件
            </SidebarRow>
            <SideBarTree
              nodes={folderItems}
              selected={fm.space === 'folder' ? fm.activeFolderId : ''}
              collapsed={collapsed}
              onSelect={onNode}
              onToggle={(id) =>
                setCollapsed((prev) => {
                  const next = new Set(prev)
                  if (next.has(id)) next.delete(id)
                  else next.add(id)
                  return next
                })
              }
            />
          </>
        ) : (
          <>
            <SidebarRow icon="folder-open" color="var(--kn-sky-500)" onClick={onOpenFolder}>
              打开文件夹…
            </SidebarRow>
            <div className="vs-empty">未打开本地文件夹</div>
          </>
        )}
      </SidebarSection>

      <div className="vs-sep" />

      <SidebarSection title="空间" icon="shield">
        <SidebarRow
          icon="folder"
          color="var(--kn-sky-500)"
          selected={fm.space === 'folder'}
          onClick={() => fm.setSpace('folder')}
        >
          文件夹
        </SidebarRow>
        <SidebarRow
          icon="tag"
          color="var(--kn-brand-500)"
          selected={fm.space === 'library'}
          onClick={() => fm.setSpace('library')}
          meta={<span className="vs-meta">{fm.libraryFiles.length}</span>}
        >
          资料空间
        </SidebarRow>
        <SidebarRow
          icon="lock"
          color="var(--kn-amber-500)"
          selected={fm.space === 'private'}
          onClick={() => fm.setSpace('private')}
          meta={<span className="vs-meta">加密</span>}
        >
          私有空间
        </SidebarRow>
      </SidebarSection>
    </div>
  )
}

// src/component/sidebar/views/FilesSidebar.vue
<!--
  FilesSidebar：文件管理侧栏（与页面目录同步）
  - 「文件夹」模式目录树：与页面共享同一棵树 / 当前目录（useFileManager），
    侧栏点目录 → 页面列表与面包屑同步；页面点 → 侧栏高亮同步
  - 空间入口：文件夹 / 资料空间 / 私有空间（与顶部 Tab 同步）
  - 折叠状态由本组件本地维护
-->
<template>
  <div class="fs">
    <SidebarSection title="目录" icon="folder">
      <!-- 已打开本地文件夹：目录树（与页面同步） -->
      <template v-if="folderOpened">
        <SidebarRow :icon="'th-large'" :selected="space === 'folder' && !activeFolderId" @click="pickAll">
          全部文件
          <template #meta><span class="fs-count">{{ folderFiles.length }}</span></template>
        </SidebarRow>

        <SideBarTree
          :nodes="folderItems"
          :selected="space === 'folder' ? activeFolderId : ''"
          :collapsed="collapsed"
          @select="onNode"
        />
      </template>

      <!-- 未打开：打开入口 -->
      <template v-else>
        <SidebarRow :icon="'folder-open'" :color="'var(--kn-sky-500)'" @click="onOpenFolder">
          打开文件夹…
        </SidebarRow>
        <div class="fs-empty">未打开本地文件夹</div>
      </template>
    </SidebarSection>

    <div class="fs-sep" />

    <SidebarSection title="空间" icon="shield">
      <SidebarRow
        :icon="'folder'"
        :color="'var(--kn-sky-500)'"
        :selected="space === 'folder'"
        @click="setSpace('folder')"
      >
        文件夹
      </SidebarRow>
      <SidebarRow
        :icon="'tag'"
        :color="'var(--kn-brand-500)'"
        :selected="space === 'library'"
        @click="setSpace('library')"
      >
        资料空间
        <template #meta><span class="fs-count">{{ libraryFiles.length }}</span></template>
      </SidebarRow>
      <SidebarRow
        :icon="'lock'"
        :color="'var(--kn-amber-500)'"
        :selected="space === 'private'"
        @click="setSpace('private')"
      >
        私有空间
        <template #meta><span class="fs-count">加密</span></template>
      </SidebarRow>
    </SidebarSection>
  </div>
</template>

<script setup lang="ts">
import { computed, ref } from 'vue'
import SidebarSection from './SidebarSection.vue'
import SidebarRow from './SidebarRow.vue'
import SideBarTree from '../SideBarTree.vue'
import type { TreeItem } from '../types'
import { useFileManager } from '../../../composables'
import type { FolderNode } from '../../../component/files'

const {
  folders,
  folderFiles,
  libraryFiles,
  space,
  activeFolderId,
  folderOpened,
  openFolder,
  setSpace,
  selectFolder,
} = useFileManager()

/** 文件夹树 → SideBarTree 节点（叶子文件夹补 folder 图标） */
function toTreeItems(nodes: FolderNode[]): TreeItem[] {
  return nodes.map((n) => ({
    id: n.id,
    label: n.name,
    icon: n.children?.length ? undefined : 'folder',
    children: n.children?.length ? toTreeItems(n.children) : undefined,
  }))
}

const folderItems = computed(() => toTreeItems(folders.value))

/** 折叠状态（本地维护） */
const collapsed = ref<Set<string>>(new Set())

function pickAll() {
  setSpace('folder')
  selectFolder('')
}

/** 打开本地文件夹（同时切到文件夹 Tab，便于看到加载与结果） */
function onOpenFolder() {
  setSpace('folder')
  openFolder()
}

/** 点目录节点：切到文件夹模式并选中该目录（与页面同步） */
function onNode(item: TreeItem) {
  setSpace('folder')
  selectFolder(item.id)
}
</script>

<style scoped>
.fs {
  display: flex;
  flex-direction: column;
  gap: 2px;
  padding-bottom: 8px;
}
.fs-sep {
  height: 1px;
  margin: 6px 10px;
  background: var(--sb-border);
}
.fs-count {
  font-size: 10px;
  opacity: 0.5;
  flex-shrink: 0;
  margin-left: 6px;
}
.fs-empty {
  padding: 4px 10px 6px;
  font-size: var(--kn-text-2xs);
  color: var(--kn-fg-subtle);
}
</style>
