// src/component/editor/CodeView.tsx
/**
 * CodeView：代码编辑区（React 版，逐行编辑）
 * - 每行 = 高亮 span + 透明 textarea 完全重叠（天然逐字对齐）
 * - Enter 分行（自动缩进）/ 行首 Backspace 合并 / ↑↓ 跨行光标 / Tab 缩进与跳转
 * - 括号自动配对、括号匹配高亮、文件级词频补全（Tab/Enter 接受）
 * - 查找替换（Ctrl+F）：Enter 下一个 / Shift+Enter 上一个 / Esc 关闭
 * - 内容经 onUpdate 回传父级（父级持有数据与未保存标记）
 *
 * React 版要点：编辑操作只 emit 内容 + 记录「待恢复的光标位置」，
 * 等父级内容回流后由 useLayoutEffect 统一恢复焦点/选区
 */
import { useCallback, useEffect, useLayoutEffect, useMemo, useRef, useState } from 'react'
import { Icon } from '../common/Icon'
import { highlightLine } from './highlight'
import type { MarkRange } from './highlight'
import { indentFor, dedent, findBracketMatch, collectWords, wordBefore, candidatesFor } from './assist'
import type { EditorFile } from '@/data/editorFiles'
import './tokens.css'
import './editor.css'

const OPEN: Record<string, string> = { '(': ')', '[': ']', '{': '}' }
const CLOSE: Record<string, string> = { ')': '(', ']': '[', '}': '{' }

interface Match {
  line: number
  start: number
  end: number
}

interface Suggestion {
  active: boolean
  line: number
  start: number
  prefix: string
  candidates: string[]
  index: number
}

const EMPTY_SUGGESTION: Suggestion = {
  active: false,
  line: 0,
  start: 0,
  prefix: '',
  candidates: [],
  index: 0,
}

export interface CodeViewProps {
  file: EditorFile
  onUpdate: (content: string) => void
  onCursor: (pos: { line: number; col: number; selected: number }) => void
}

export function CodeView({ file, onUpdate, onCursor }: CodeViewProps) {
  const content = file.content
  const lines = useMemo(() => content.split('\n'), [content])
  const lineCount = Math.max(1, lines.length)
  const wordFreq = useMemo(() => collectWords(lines), [lines])

  /* ==================== 滚动 / 行号 ==================== */

  const scrollRef = useRef<HTMLDivElement>(null)
  const [scrollTop, setScrollTop] = useState(0)
  const [activeLine, setActiveLine] = useState(1)

  /** 行高（px；挂载时从 --ed-line-height 读取，保证与渲染一致） */
  const lineHRef = useRef(21)
  useEffect(() => {
    const v = getComputedStyle(document.documentElement).getPropertyValue('--ed-line-height')
    const n = parseFloat(v)
    if (n > 0) lineHRef.current = n
  }, [])

  const onScroll = () => {
    const sc = scrollRef.current
    if (sc) setScrollTop(sc.scrollTop)
  }

  /* ==================== 行 textarea refs ==================== */

  const lineRefs = useRef<(HTMLTextAreaElement | null)[]>([])

  /**
   * 待恢复的光标：编辑后父级内容回流，再由 layout effect 统一设置焦点与选区。
   * focus: 是否需要重新聚焦该行（Enter/合并等跨行操作）
   */
  const pendingCaret = useRef<{ line: number; start: number; focus: boolean } | null>(null)

  /* ==================== 智能辅助：括号配对 + 补全 ==================== */

  const [activeBracket, setActiveBracket] = useState<{
    open: { line: number; col: number }
    close: { line: number; col: number }
  } | null>(null)
  const [suggestion, setSuggestion] = useState<Suggestion>(EMPTY_SUGGESTION)

  const closeSuggestion = useCallback(() => setSuggestion(EMPTY_SUGGESTION), [])

  const refreshAssist = useCallback(
    (i: number, ta: HTMLTextAreaElement) => {
      const col = ta.selectionStart
      const ln = lines[i] ?? ''

      /* 括号配对：光标停在括号字符上（无选区）才找配对 */
      if (ta.selectionStart === ta.selectionEnd) {
        const hit = findBracketMatch(lines, i, col)
        setActiveBracket(hit ? { open: { line: i, col }, close: hit } : null)
      } else {
        setActiveBracket(null)
      }

      /* 补全候选：光标前有单词前缀 且 未打开查找面板 */
      if (!findOpenRef.current) {
        const { start, prefix } = wordBefore(ln, col)
        const cands = prefix ? candidatesFor(wordFreq, prefix) : []
        if (cands.length) {
          setSuggestion({ active: true, line: i, start, prefix, candidates: cands, index: 0 })
        } else {
          closeSuggestion()
        }
      } else {
        closeSuggestion()
      }
    },
    [lines, wordFreq, closeSuggestion]
  )

  /** emitCursor 的 ref 实现（供稳定回调使用；总是引用最新实现） */
  const emitCursorRef = useRef<(i: number, ta: HTMLTextAreaElement) => void>(() => {})
  useEffect(() => {
    emitCursorRef.current = (i, ta) => {
      setActiveLine(i + 1)
      onCursor({
        line: i + 1,
        col: ta.selectionStart + 1,
        selected: ta.selectionEnd - ta.selectionStart,
      })
      refreshAssist(i, ta)
    }
  }, [onCursor, refreshAssist])

  const emitCursorStable = useCallback((i: number, ta: HTMLTextAreaElement) => {
    emitCursorRef.current(i, ta)
  }, [])

  /* ==================== 编辑操作（emit 内容 + 记录待恢复光标） ==================== */

  const commitLines = useCallback(
    (next: string[], caret?: { line: number; start: number; focus?: boolean }) => {
      if (caret) pendingCaret.current = { line: caret.line, start: caret.start, focus: caret.focus ?? true }
      onUpdate(next.join('\n'))
    },
    [onUpdate]
  )

  const insertIntoLine = useCallback(
    (i: number, text: string, s: number, e: number) => {
      const next = lines.slice()
      next[i] = next[i].slice(0, s) + text + next[i].slice(e)
      commitLines(next, { line: i, start: s + text.length })
    },
    [lines, commitLines]
  )

  const splitLine = useCallback(
    (i: number, s: number, e: number) => {
      const next = lines.slice()
      const head = next[i].slice(0, s)
      const tail = next[i].slice(e)
      const indent = indentFor(lines[i - 1] ?? '', tail)
      next[i] = head
      next.splice(i + 1, 0, indent + tail)
      commitLines(next, { line: i + 1, start: indent.length })
    },
    [lines, commitLines]
  )

  const mergeLines = useCallback(
    (i: number) => {
      const next = lines.slice()
      const cur = next[i]
      next[i - 1] += cur
      const mergePos = next[i - 1].length - cur.length
      next.splice(i, 1)
      commitLines(next, { line: i - 1, start: mergePos })
    },
    [lines, commitLines]
  )

  /** 内容回流后恢复焦点/选区（nextTick 语义） */
  useLayoutEffect(() => {
    const p = pendingCaret.current
    if (!p) return
    pendingCaret.current = null
    const ta = lineRefs.current[p.line]
    if (!ta) return
    if (p.focus) ta.focus()
    const pos = Math.min(p.start, ta.value.length)
    ta.setSelectionRange(pos, pos)
    emitCursorStable(p.line, ta)
  }, [content, emitCursorStable])

  /* ==================== 键盘处理 ==================== */

  const acceptSuggestion = useCallback(() => {
    const sug = suggestion
    if (!sug.active) return
    const cand = sug.candidates[sug.index]
    if (!cand) return
    const next = lines.slice()
    const ln = next[sug.line]
    next[sug.line] = ln.slice(0, sug.start) + cand + ln.slice(sug.start + sug.prefix.length)
    closeSuggestion()
    commitLines(next, { line: sug.line, start: sug.start + cand.length })
  }, [suggestion, lines, closeSuggestion, commitLines])

  const acceptIndex = (idx: number) => {
    const sug = suggestion
    if (!sug.active) return
    const cand = sug.candidates[idx]
    if (!cand) return
    const next = lines.slice()
    const ln = next[sug.line]
    next[sug.line] = ln.slice(0, sug.start) + cand + ln.slice(sug.start + sug.prefix.length)
    closeSuggestion()
    commitLines(next, { line: sug.line, start: sug.start + cand.length })
  }

  const cycleSuggestion = (dir: number) => {
    setSuggestion((s) => {
      const n = s.candidates.length
      if (!n) return s
      return { ...s, index: (s.index + dir + n) % n }
    })
  }

  const onLineKeydown = (i: number, e: React.KeyboardEvent<HTMLTextAreaElement>) => {
    const ta = e.currentTarget
    const len = lines.length
    const s = ta.selectionStart
    const eSel = ta.selectionEnd
    const ln = lines[i]

    /* 补全弹层优先 */
    if (suggestion.active) {
      if (e.key === 'Tab' || e.key === 'Enter') {
        e.preventDefault()
        acceptSuggestion()
        return
      }
      if (e.key === 'ArrowDown' || e.key === 'ArrowUp') {
        e.preventDefault()
        cycleSuggestion(e.key === 'ArrowDown' ? 1 : -1)
        return
      }
      if (e.key === 'Escape') {
        e.preventDefault()
        closeSuggestion()
        return
      }
    }

    /* 括号自动补全 */
    if (s === eSel && OPEN[e.key]) {
      e.preventDefault()
      insertIntoLine(i, e.key + OPEN[e.key], s, eSel)
      return
    }
    /* 跳过后随的同类右括号 */
    if (s === eSel && CLOSE[e.key] && ln.charAt(s) === e.key) {
      e.preventDefault()
      ta.setSelectionRange(s + 1, s + 1)
      return
    }
    /* 成对删除 */
    if (
      e.key === 'Backspace' &&
      s > 0 &&
      s === eSel &&
      OPEN[ln.charAt(s - 1)] &&
      ln.charAt(s) === OPEN[ln.charAt(s - 1)]
    ) {
      e.preventDefault()
      const next = lines.slice()
      next[i] = ln.slice(0, s - 1) + ln.slice(s + 1)
      commitLines(next, { line: i, start: s - 1 })
      return
    }

    if (e.key === 'Tab') {
      e.preventDefault()
      if (e.shiftKey) {
        const next = lines.slice()
        const orig = next[i]
        next[i] = dedent(orig)
        const diff = orig.length - next[i].length
        commitLines(next, { line: i, start: Math.max(0, s - diff) })
      } else {
        insertIntoLine(i, '  ', s, eSel)
      }
    } else if (e.key === 'Enter') {
      e.preventDefault()
      splitLine(i, s, eSel)
    } else if (e.key === 'Backspace' && s === 0 && eSel === 0 && i > 0) {
      e.preventDefault()
      mergeLines(i)
    } else if (e.key === 'ArrowUp' || e.key === 'ArrowDown') {
      const target = i + (e.key === 'ArrowUp' ? -1 : 1)
      if (target < 0 || target >= len) return
      e.preventDefault()
      const col = s
      const tta = lineRefs.current[target]
      if (!tta) return
      const pos = Math.min(col, tta.value.length)
      tta.focus()
      tta.setSelectionRange(pos, pos)
      emitCursorStable(target, tta)
      scrollLineIntoView(target)
    }
  }

  /* ==================== 查找 / 替换 ==================== */

  const [findOpen, setFindOpen] = useState(false)
  const findOpenRef = useRef(false)
  useEffect(() => {
    findOpenRef.current = findOpen
  }, [findOpen])
  const [findQuery, setFindQuery] = useState('')
  const [replaceText, setReplaceText] = useState('')
  const [matches, setMatches] = useState<Match[]>([])
  const [activeIndex, setActiveIndex] = useState(-1)
  const findInputRef = useRef<HTMLInputElement>(null)
  const replaceInputRef = useRef<HTMLInputElement>(null)

  const computeMatches = useCallback(
    (q: string): Match[] => {
      const query = q.toLowerCase()
      if (!query) return []
      const res: Match[] = []
      lines.forEach((ln, li) => {
        const low = ln.toLowerCase()
        let idx = low.indexOf(query)
        while (idx !== -1) {
          res.push({ line: li, start: idx, end: idx + query.length })
          idx = low.indexOf(query, idx + query.length)
        }
      })
      return res
    },
    [lines]
  )

  const scrollLineIntoView = useCallback((li: number) => {
    const sc = scrollRef.current
    if (!sc) return
    const LINE_H = lineHRef.current
    const y = li * LINE_H
    if (y < sc.scrollTop || y + LINE_H > sc.scrollTop + sc.clientHeight) {
      sc.scrollTop = Math.max(0, y - LINE_H * 2)
    }
    setScrollTop(sc.scrollTop)
  }, [])

  const selectMatch = useCallback(
    (list: Match[], index: number) => {
      const m = list[index]
      if (!m) return
      const ta = lineRefs.current[m.line]
      if (!ta) return
      ta.focus()
      ta.setSelectionRange(m.start, m.end)
      scrollLineIntoView(m.line)
      emitCursorStable(m.line, ta)
    },
    [scrollLineIntoView, emitCursorStable]
  )

  const openFind = useCallback(() => {
    setFindOpen(true)
    /* 带上当前选中词 */
    setFindQuery((q) => {
      if (q) return q
      for (const ta of lineRefs.current) {
        if (ta && document.activeElement === ta && ta.selectionStart !== ta.selectionEnd) {
          return ta.value.slice(ta.selectionStart, ta.selectionEnd)
        }
      }
      return q
    })
  }, [])

  /* 打开查找后聚焦输入框 */
  useEffect(() => {
    if (findOpen) {
      const t = window.setTimeout(() => {
        findInputRef.current?.focus()
        findInputRef.current?.select()
      }, 20)
      return () => window.clearTimeout(t)
    }
  }, [findOpen])

  /* 查询词变化 → 重算命中并选中第一个 */
  useEffect(() => {
    if (!findOpen) return
    const list = computeMatches(findQuery)
    setMatches(list)
    const idx = list.length ? 0 : -1
    setActiveIndex(idx)
    if (idx >= 0) selectMatch(list, idx)
  }, [findQuery, findOpen, computeMatches, selectMatch])

  /* 内容变化（编辑后）：重算命中位置，避免高亮/跳转错位 */
  useEffect(() => {
    if (!findQuery) return
    const list = computeMatches(findQuery)
    setMatches(list)
    setActiveIndex((i) => Math.min(Math.max(i, 0), list.length - 1))
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [content])

  const findNext = () => {
    if (!matches.length) return
    const next = (activeIndex + 1) % matches.length
    setActiveIndex(next)
    selectMatch(matches, next)
  }

  const findPrev = () => {
    if (!matches.length) return
    const prev = (activeIndex - 1 + matches.length) % matches.length
    setActiveIndex(prev)
    selectMatch(matches, prev)
  }

  const replaceCurrent = () => {
    const m = matches[activeIndex]
    if (!m) return
    const next = lines.slice()
    const ln = next[m.line]
    next[m.line] = ln.slice(0, m.start) + replaceText + ln.slice(m.end)
    commitLines(next, { line: m.line, start: m.start, focus: false })
    const list = computeMatches(findQuery)
    setMatches(list)
    const after = m.start + replaceText.length
    const idx = list.findIndex(
      (x) => x.line > m.line || (x.line === m.line && x.start >= after)
    )
    const nextIdx = idx >= 0 ? idx : Math.max(0, list.length - 1)
    setActiveIndex(nextIdx)
    window.setTimeout(() => selectMatch(list, nextIdx), 0)
  }

  const replaceAll = () => {
    if (!matches.length) return
    const next = lines.slice()
    for (let i = matches.length - 1; i >= 0; i--) {
      const m = matches[i]
      next[m.line] = next[m.line].slice(0, m.start) + replaceText + next[m.line].slice(m.end)
    }
    commitLines(next)
    const list = computeMatches(findQuery)
    setMatches(list)
    setActiveIndex(list.length ? 0 : -1)
  }

  /* ==================== 高亮标记 ==================== */

  const marksForLine = (li: number): MarkRange[] | undefined => {
    const arr: MarkRange[] = []
    for (const m of matches) {
      if (m.line === li) {
        arr.push({
          start: m.start,
          end: m.end,
          current: m === matches[activeIndex],
          kind: 'find',
        })
      }
    }
    if (activeBracket) {
      if (activeBracket.open.line === li) {
        arr.push({
          start: activeBracket.open.col,
          end: activeBracket.open.col + 1,
          kind: 'bracket',
        })
      }
      if (activeBracket.close.line === li) {
        arr.push({
          start: activeBracket.close.col,
          end: activeBracket.close.col + 1,
          kind: 'bracket',
        })
      }
    }
    return arr.length ? arr : undefined
  }

  /* ==================== 补全弹层定位 ==================== */

  const suggestPos = useMemo(() => {
    const sug = suggestion
    const sc = scrollRef.current
    if (!sug.active || !sc) return { left: 0, top: 0 }
    const meas = document.createElement('span')
    meas.className = 'ed-hl-text'
    meas.style.position = 'absolute'
    meas.style.visibility = 'hidden'
    sc.appendChild(meas)
    meas.textContent = (lines[sug.line] ?? '').slice(0, sug.start)
    const w = meas.offsetWidth
    meas.remove()
    return {
      left: w - sc.scrollLeft,
      top: (sug.line + 1) * lineHRef.current - sc.scrollTop,
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [suggestion, scrollTop, lines])

  /* ==================== 全局快捷键（Ctrl+F / Esc） ==================== */

  const onEditorKeydown = (e: React.KeyboardEvent) => {
    if ((e.metaKey || e.ctrlKey) && e.key.toLowerCase() === 'f') {
      e.preventDefault()
      openFind()
    } else if (e.key === 'Escape') {
      setFindOpen(false)
    }
  }

  /* 切换文件：重置滚动与焦点 */
  useEffect(() => {
    setActiveLine(1)
    setScrollTop(0)
    const sc = scrollRef.current
    if (sc) sc.scrollTop = 0
    lineRefs.current[0]?.focus()
    setActiveBracket(null)
    closeSuggestion()
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [file.id])

  useEffect(() => {
    lineRefs.current[0]?.focus()
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [])

  /* 内容变化：括号配对/补全位置会失效，清除 */
  useEffect(() => {
    setActiveBracket(null)
    if (!findOpenRef.current) closeSuggestion()
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [content])

  /* ==================== 渲染 ==================== */

  return (
    <div className="ed-code" onKeyDown={onEditorKeydown}>
      {/* 行号栏（跟随滚动） */}
      <div className="ed-gutter" aria-hidden="true">
        <div className="ed-gutter-inner" style={{ transform: `translateY(${-scrollTop}px)` }}>
          {Array.from({ length: lineCount }, (_, i) => (
            <div key={i + 1} className={`ed-ln${i + 1 === activeLine ? ' is-active' : ''}`}>
              {i + 1}
            </div>
          ))}
        </div>
      </div>

      {/* 滚动容器 */}
      <div className="ed-scroll" ref={scrollRef} onScroll={onScroll}>
        <div className="ed-lines">
          {lines.map((line, i) => (
            <div key={i} className={`ed-line${i + 1 === activeLine ? ' is-active' : ''}`}>
              <span
                className="ed-hl-text"
                dangerouslySetInnerHTML={{ __html: highlightLine(line, marksForLine(i)) }}
              />
              <textarea
                ref={(el) => {
                  lineRefs.current[i] = el
                }}
                className="ed-line-input"
                rows={1}
                value={line}
                spellCheck={false}
                autoComplete="off"
                autoCorrect="off"
                autoCapitalize="off"
                wrap="off"
                onChange={(e) => {
                  const next = lines.slice()
                  next[i] = e.target.value
                  onUpdate(next.join('\n'))
                  queueMicrotask(() => emitCursorStable(i, e.target))
                }}
                onKeyDown={(e) => onLineKeydown(i, e)}
                onKeyUp={(e) => emitCursorStable(i, e.currentTarget)}
                onMouseUp={(e) => emitCursorStable(i, e.currentTarget)}
                onSelect={(e) => emitCursorStable(i, e.currentTarget)}
                onFocus={(e) => emitCursorStable(i, e.currentTarget)}
              />
            </div>
          ))}

          {content === '' && <div className="ed-empty">空文件</div>}
        </div>
      </div>

      {/* 补全弹层 */}
      {suggestion.active && (
        <div className="ed-suggest" style={suggestPos} onMouseDown={(e) => e.preventDefault()}>
          {suggestion.candidates.map((c, idx) => (
            <div
              key={c}
              className={`ed-suggest-item${idx === suggestion.index ? ' is-active' : ''}`}
              onMouseDown={(e) => {
                e.preventDefault()
                acceptIndex(idx)
              }}
            >
              {c}
            </div>
          ))}
        </div>
      )}

      {/* 查找/替换 */}
      {findOpen && (
        <div
          className="ed-find"
          onKeyDown={(e) => {
            e.stopPropagation()
            if (e.key === 'Enter' && e.shiftKey) {
              e.preventDefault()
              findPrev()
            } else if (e.key === 'Enter') {
              e.preventDefault()
              findNext()
            } else if (e.key === 'Escape') {
              e.preventDefault()
              setFindOpen(false)
            }
          }}
        >
          <div className="ed-find-row">
            <input
              ref={findInputRef}
              className="ed-find-input"
              type="text"
              placeholder="查找"
              value={findQuery}
              onChange={(e) => setFindQuery(e.target.value)}
            />
            <span className="ed-find-count">
              {matches.length > 0 ? `${activeIndex + 1}/${matches.length}` : '无结果'}
            </span>
            <button className="ed-find-btn" title="上一个 (Shift+Enter)" onClick={findPrev}>
              <Icon name="chevron-up" size={12} />
            </button>
            <button className="ed-find-btn" title="下一个 (Enter)" onClick={findNext}>
              <Icon name="chevron-down" size={12} />
            </button>
            <button className="ed-find-btn" title="替换" onClick={replaceCurrent}>
              替换
            </button>
            <button className="ed-find-btn" title="全部替换" onClick={replaceAll}>
              全部替换
            </button>
            <button className="ed-find-btn" title="关闭 (Esc)" onClick={() => setFindOpen(false)}>
              <Icon name="times" size={12} />
            </button>
          </div>
          <div className="ed-find-row">
            <input
              ref={replaceInputRef}
              className="ed-find-input"
              type="text"
              placeholder="替换为"
              value={replaceText}
              onChange={(e) => setReplaceText(e.target.value)}
              onKeyDown={(e) => {
                if (e.key === 'Enter') {
                  e.preventDefault()
                  replaceCurrent()
                }
              }}
            />
          </div>
        </div>
      )}
    </div>
  )
}

// src/component/editor/CodeView.vue
<!--
  CodeView：代码编辑区（逐行编辑，VS Code 风格，前端演示版）
  - 每行 = 高亮 <span> + 透明 textarea 完全重叠，天然逐字对齐（无需任何字体/滚动同步）
  - 行操作：Enter 分行、行首 Backspace 合并、↑/↓ 跨行移光标、Tab 插 2 空格
  - 查找/替换（Ctrl+F，Enter 下一个，Shift+Enter 上一个，Esc 关闭）
  - 内容通过 update 事件回传父级（Editor.vue 持有数据与未保存标记）
-->
<template>
  <div class="ed-code" @keydown.stop="onEditorKeydown">
    <!-- 行号栏（固定不横滚，垂直随 scroller 同步） -->
    <div class="ed-gutter" aria-hidden="true">
      <div class="ed-gutter-inner" :style="{ transform: `translateY(${-scrollTop}px)` }">
        <div
          v-for="i in lineCount"
          :key="i"
          class="ed-ln"
          :class="{ 'is-active': i === activeLine }"
        >{{ i }}</div>
      </div>
    </div>

    <!-- 滚动容器：行内容一起滚动，行内高亮与输入框自动同步 -->
    <div class="ed-scroll" ref="scrollRef" @scroll="onScroll">
      <div class="ed-lines">
        <div
          v-for="(line, i) in lines"
          :key="i"
          class="ed-line"
          :class="{ 'is-active': i + 1 === activeLine }"
        >
          <!-- 高亮层（不接收事件；v-html 每敲键重渲，不影响输入框光标） -->
          <span class="ed-hl-text" v-html="highlightLine(line, marksForLine(i))" />
          <!-- 编辑层：透明文字 + 可见光标，单行原生编辑 -->
          <textarea
            :ref="(el) => setLineRef(i, el)"
            class="ed-line-input"
            rows="1"
            :value="line"
            spellcheck="false"
            autocomplete="off"
            autocorrect="off"
            autocapitalize="off"
            wrap="off"
            @input="onLineInput(i, $event)"
            @keydown="onLineKeydown(i, $event)"
            @keyup="(e) => onCursorEvent(i, e)"
            @mouseup="(e) => onCursorEvent(i, e)"
            @select="(e) => onCursorEvent(i, e)"
            @focus="(e) => onCursorEvent(i, e)"
          ></textarea>
        </div>

        <div v-if="content === ''" class="ed-empty">空文件</div>
      </div>
    </div>

    <!-- 查找/替换面板 -->
    <div v-if="findOpen" class="ed-find" @keydown.stop="onFindKeydown">
      <div class="ed-find-row">
        <input
          ref="findInputRef"
          v-model="findQuery"
          class="ed-find-input"
          type="text"
          placeholder="查找"
          @input="onFindInput"
        />
        <span class="ed-find-count">
          {{ matches.length > 0 ? `${activeIndex + 1}/${matches.length}` : '无结果' }}
        </span>
        <button class="ed-find-btn" title="上一个 (Shift+Enter)" @click="findPrev">
          <Icon name="chevron-up" :size="12" />
        </button>
        <button class="ed-find-btn" title="下一个 (Enter)" @click="findNext">
          <Icon name="chevron-down" :size="12" />
        </button>
        <button class="ed-find-btn" title="替换 (Enter)" @click="replaceCurrent">替换</button>
        <button class="ed-find-btn" title="全部替换" @click="replaceAll">全部替换</button>
        <button class="ed-find-btn" title="关闭 (Esc)" @click="findOpen = false">
          <Icon name="times" :size="12" />
        </button>
      </div>
      <div class="ed-find-row">
        <input
          v-model="replaceText"
          class="ed-find-input"
          type="text"
          placeholder="替换为"
          @keydown.enter.prevent="replaceCurrent"
        />
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { computed, nextTick, onMounted, ref, watch } from 'vue'
import { Icon } from '../common'
import { highlightLine } from './highlight'
import type { MarkRange } from './highlight'
import type { EditorFile } from '../../data/editorFiles'

const props = defineProps<{
  file: EditorFile
}>()

const emit = defineEmits<{
  /** 内容变更（父级持有数据，负责标记未保存） */
  update: [content: string]
  /** 光标/选区变化：行/列/选中字符数 */
  cursor: [{ line: number; col: number; selected: number }]
}>()

const content = computed(() => props.file.content)
/** 数据模型：逐行数组，改动时以 \n 拼回整体 emit */
const lines = computed(() => content.value.split('\n'))
const lineCount = computed(() => Math.max(1, lines.value.length))

/* =================== 滚动 / 行号 =================== */

const scrollRef = ref<HTMLElement>()
const scrollTop = ref(0)
const activeLine = ref(1)

/** 行高（px，滚动计算用；运行时从 --ed-line-height 读取，避免与 token 漂移） */
let LINE_H = 21

function onScroll() {
  const sc = scrollRef.value
  if (sc) scrollTop.value = sc.scrollTop
}

/* =================== 行 refs =================== */

const lineRefs: (HTMLTextAreaElement | null)[] = []
function setLineRef(i: number, el: unknown) {
  lineRefs[i] = el ? (el as HTMLTextAreaElement) : null
}

/* =================== 光标 / 选区 =================== */

function onCursorEvent(i: number, e: Event) {
  emitCursor(i, e.target as HTMLTextAreaElement)
}

function emitCursor(i: number, ta: HTMLTextAreaElement) {
  if (!ta) return
  activeLine.value = i + 1
  emit('cursor', {
    line: i + 1,
    col: ta.selectionStart + 1,
    selected: ta.selectionEnd - ta.selectionStart,
  })
}

/* =================== 编辑 =================== */

function onLineInput(i: number, e: Event) {
  const ta = e.target as HTMLTextAreaElement
  const next = lines.value.slice()
  next[i] = ta.value
  emit('update', next.join('\n'))
  emitCursor(i, ta)
}

function onLineKeydown(i: number, e: KeyboardEvent) {
  const ta = lineRefs[i]
  if (!ta) return
  const len = lines.value.length
  const s = ta.selectionStart
  const eSel = ta.selectionEnd

  // 查找面板内的按键由面板自己处理，不走到这里（面板已 @keydown.stop）
  if (e.key === 'Tab') {
    e.preventDefault()
    insertIntoLine(i, '  ', s, eSel)
  } else if (e.key === 'Enter') {
    e.preventDefault()
    splitLine(i, s, eSel)
  } else if (e.key === 'Backspace' && s === 0 && eSel === 0 && i > 0) {
    e.preventDefault()
    mergeLines(i)
  } else if (e.key === 'ArrowUp' || e.key === 'ArrowDown') {
    const target = i + (e.key === 'ArrowUp' ? -1 : 1)
    if (target < 0 || target >= len) return
    e.preventDefault()
    const col = s
    nextTick(() => {
      const tta = lineRefs[target]
      if (!tta) return
      const pos = Math.min(col, tta.value.length)
      tta.focus()
      tta.setSelectionRange(pos, pos)
      emitCursor(target, tta)
      scrollLineIntoView(target)
    })
  }
}

/** 在行内指定区间插入文本（Tab 用） */
function insertIntoLine(i: number, text: string, s: number, e: number) {
  const next = lines.value.slice()
  next[i] = next[i].slice(0, s) + text + next[i].slice(e)
  emit('update', next.join('\n'))
  nextTick(() => {
    const ta = lineRefs[i]
    if (!ta) return
    const pos = s + text.length
    ta.focus()
    ta.setSelectionRange(pos, pos)
    emitCursor(i, ta)
  })
}

/** Enter：把当前行从光标处拆成两行 */
function splitLine(i: number, s: number, e: number) {
  const next = lines.value.slice()
  const head = next[i].slice(0, s)
  const tail = next[i].slice(e)
  next[i] = head
  next.splice(i + 1, 0, tail)
  emit('update', next.join('\n'))
  nextTick(() => {
    const nta = lineRefs[i + 1]
    if (!nta) return
    nta.focus()
    nta.setSelectionRange(0, 0)
    emitCursor(i + 1, nta)
  })
}

/** 行首 Backspace：与上一行合并 */
function mergeLines(i: number) {
  const next = lines.value.slice()
  const cur = next[i]
  next[i - 1] += cur
  next.splice(i, 1)
  // 光标落在合并后行的前段末尾（= 上一行原长度），必须在 emit 前算好
  const mergePos = next[i - 1].length - cur.length
  emit('update', next.join('\n'))
  nextTick(() => {
    const pta = lineRefs[i - 1]
    if (!pta) return
    pta.focus()
    pta.setSelectionRange(mergePos, mergePos)
    emitCursor(i - 1, pta)
  })
}

/** 编辑器级按键（冒泡到外层）：Ctrl+F 打开查找 */
function onEditorKeydown(e: KeyboardEvent) {
  if ((e.metaKey || e.ctrlKey) && e.key.toLowerCase() === 'f') {
    e.preventDefault()
    openFind()
  } else if (e.key === 'Escape') {
    findOpen.value = false
  }
}

/* =================== 查找 / 替换 =================== */

interface Match { line: number; start: number; end: number }

const findOpen = ref(false)
const findQuery = ref('')
const replaceText = ref('')
const matches = ref<Match[]>([])
const activeIndex = ref(0)
const findInputRef = ref<HTMLInputElement | null>(null)

function openFind() {
  findOpen.value = true
  if (!findQuery.value) {
    // 打开时自动带上当前选中词（取焦点行的选区）
    for (const ta of lineRefs) {
      if (ta && document.activeElement === ta && ta.selectionStart !== ta.selectionEnd) {
        findQuery.value = ta.value.slice(ta.selectionStart, ta.selectionEnd)
        break
      }
    }
  }
  nextTick(() => {
    findInputRef.value?.focus()
    findInputRef.value?.select()
  })
  onFindInput()
}

function computeMatches(q: string): Match[] {
  const query = q.toLowerCase()
  if (!query) return []
  const res: Match[] = []
  lines.value.forEach((ln, li) => {
    const low = ln.toLowerCase()
    let idx = low.indexOf(query)
    while (idx !== -1) {
      res.push({ line: li, start: idx, end: idx + query.length })
      idx = low.indexOf(query, idx + query.length)
    }
  })
  return res
}

function onFindInput() {
  matches.value = computeMatches(findQuery.value)
  activeIndex.value = matches.value.length ? 0 : -1
  selectMatch()
}

function findNext() {
  if (!matches.value.length) return
  activeIndex.value = (activeIndex.value + 1) % matches.value.length
  selectMatch()
}

function findPrev() {
  if (!matches.value.length) return
  activeIndex.value = (activeIndex.value - 1 + matches.value.length) % matches.value.length
  selectMatch()
}

function selectMatch() {
  const m = matches.value[activeIndex.value]
  if (!m) return
  const ta = lineRefs[m.line]
  if (!ta) return
  ta.focus()
  ta.setSelectionRange(m.start, m.end)
  scrollLineIntoView(m.line)
  emitCursor(m.line, ta)
}

/** 让某行滚入可视区（行高固定，纯数学计算，无需字体度量） */
function scrollLineIntoView(li: number) {
  const sc = scrollRef.value
  if (!sc) return
  const y = li * LINE_H
  if (y < sc.scrollTop || y + LINE_H > sc.scrollTop + sc.clientHeight) {
    sc.scrollTop = Math.max(0, y - LINE_H * 2)
  }
  onScroll()
}

function onFindKeydown(e: KeyboardEvent) {
  if (e.key === 'Enter' && e.shiftKey) { e.preventDefault(); findPrev() }
  else if (e.key === 'Enter') { e.preventDefault(); findNext() }
  else if (e.key === 'Escape') { e.preventDefault(); findOpen.value = false }
}

/** 当前行的查找命中区段（current 标记当前匹配） */
function marksForLine(li: number): MarkRange[] | undefined {
  const arr = matches.value.filter((m) => m.line === li)
  if (!arr.length) return undefined
  return arr.map((m) => ({
    start: m.start,
    end: m.end,
    current: m === matches.value[activeIndex.value],
  }))
}

function replaceCurrent() {
  const m = matches.value[activeIndex.value]
  if (!m) return
  const next = lines.value.slice()
  const ln = next[m.line]
  next[m.line] = ln.slice(0, m.start) + replaceText.value + ln.slice(m.end)
  emit('update', next.join('\n'))
  onFindInput()
  // 活动项前进到替换位置之后最近的匹配
  const after = m.start + replaceText.value.length
  const idx = matches.value.findIndex((x) => x.line > m.line || (x.line === m.line && x.start >= after))
  activeIndex.value = idx >= 0 ? idx : Math.max(0, matches.value.length - 1)
  selectMatch()
}

function replaceAll() {
  if (!matches.value.length) return
  const next = lines.value.slice()
  // 从后往前替换，保证行内索引不偏移
  for (let i = matches.value.length - 1; i >= 0; i--) {
    const m = matches.value[i]
    next[m.line] = next[m.line].slice(0, m.start) + replaceText.value + next[m.line].slice(m.end)
  }
  emit('update', next.join('\n'))
  matches.value = computeMatches(findQuery.value)
  activeIndex.value = matches.value.length ? 0 : -1
}

onMounted(() => {
  // 行高从 token 读取（--ed-line-height），保证滚动计算与渲染一致
  const v = getComputedStyle(document.documentElement).getPropertyValue('--ed-line-height')
  const n = parseFloat(v)
  if (n > 0) LINE_H = n
  lineRefs[0]?.focus()
})

/* =================== 内容/文件变化 =================== */

/** 编辑代码后，查找命中的行内位置会失效，需要重算（否则高亮/跳转错位） */
watch(lines, () => {
  if (findQuery.value) {
    matches.value = computeMatches(findQuery.value)
    if (activeIndex.value > matches.value.length - 1) activeIndex.value = matches.value.length - 1
  }
})

/** 切换文件（KeepAlive 下组件常驻）：重置滚动与焦点 */
watch(
  () => props.file.id,
  () => {
    activeLine.value = 1
    scrollTop.value = 0
    const sc = scrollRef.value
    if (sc) sc.scrollTop = 0
    lineRefs[0]?.focus()
  }
)
</script>

<style scoped>
.ed-code {
  position: relative;
  flex: 1;
  min-height: 0;
  display: flex;
  overflow: hidden;
  background: var(--ed-bg);
  color: var(--ed-fg);
  cursor: text;
}

/* ==================== 行号栏 ==================== */
.ed-gutter {
  flex-shrink: 0;
  width: 56px;
  overflow: hidden;
  user-select: none;
  -webkit-user-select: none;
}
.ed-gutter-inner {
  will-change: transform;
}
.ed-ln {
  height: var(--ed-line-height);
  line-height: var(--ed-line-height);
  padding-right: 14px;
  text-align: right;
  color: var(--ed-gutter-fg);
  transition: color var(--kn-dur-fast);
}
.ed-gutter:hover .ed-ln { color: var(--ed-gutter-fg-hover); }
.ed-ln.is-active { color: var(--ed-gutter-fg-active); }

/* ==================== 滚动容器 / 行 ==================== */
.ed-scroll {
  flex: 1;
  min-width: 0;
  overflow: auto;
}
.ed-lines {
  width: max-content;
  min-width: 100%;
}
.ed-line {
  position: relative;
  height: var(--ed-line-height);
}
.ed-line.is-active {
  background: var(--ed-line-active-bg);
}

/* 高亮层：留在文档流内（inline-block），让行的固有宽度=文本宽度，
   这样长行能被外层容器横向滚动；textarea 绝对定位覆盖它 */
.ed-hl-text {
  display: inline-block;
  height: var(--ed-line-height);
  line-height: var(--ed-line-height);
  font-family: var(--ed-font);
  font-size: var(--ed-font-size);
  font-variant-ligatures: none;
  letter-spacing: normal;
  tab-size: 2;
  white-space: pre;
  word-break: normal;
  overflow-wrap: normal;
  pointer-events: none;
}

/* 编辑层：透明文字 + 可见光标，单行、不内滚（滚动交给外层容器） */
.ed-line-input {
  position: absolute;
  top: 0;
  left: 0;
  width: 100%;
  height: var(--ed-line-height);
  padding: 0;
  border: 0;
  outline: 0;
  margin: 0;
  resize: none;
  overflow: hidden;
  background: transparent;
  color: transparent;
  caret-color: var(--ed-fg);
  font-family: var(--ed-font);
  font-size: var(--ed-font-size);
  line-height: var(--ed-line-height);
  font-variant-ligatures: none;
  letter-spacing: normal;
  tab-size: 2;
  white-space: pre;
  box-sizing: border-box;
}
.ed-line-input::selection {
  background: rgba(99, 102, 241, 0.25);
  color: transparent;
}

/* 空文件提示 */
.ed-empty {
  position: absolute;
  inset: 0;
  display: flex;
  align-items: center;
  justify-content: center;
  color: var(--ed-gutter-fg);
  font-family: var(--kn-font-sans);
  pointer-events: none;
}

/* ==================== 查找/替换面板 ==================== */
.ed-find {
  position: absolute;
  right: 12px;
  bottom: 8px;
  z-index: 20;
  display: flex;
  flex-direction: column;
  gap: 6px;
  padding: 8px;
  background: var(--ed-find-bg);
  border: 1px solid var(--ed-find-border);
  border-radius: var(--kn-radius-lg);
  box-shadow: var(--kn-shadow-lg);
  animation: ed-find-in var(--kn-dur-base) var(--kn-ease-out);
}
@keyframes ed-find-in {
  from { opacity: 0; transform: translateY(4px); }
  to   { opacity: 1; transform: translateY(0); }
}
.ed-find-row {
  display: flex;
  align-items: center;
  gap: 6px;
}
.ed-find-input {
  width: 200px;
  padding: 4px 8px;
  border: 1px solid var(--ed-find-border);
  border-radius: var(--kn-radius-sm);
  background: var(--kn-bg-elev);
  color: var(--ed-fg);
  font: inherit;
  font-size: var(--kn-text-sm);
  outline: none;
}
.ed-find-input:focus {
  border-color: var(--kn-brand-500);
}
.ed-find-count {
  min-width: 52px;
  text-align: center;
  font-size: var(--kn-text-xs);
  color: var(--ed-status-fg);
  white-space: nowrap;
}
.ed-find-btn {
  display: inline-flex;
  align-items: center;
  justify-content: center;
  height: 22px;
  padding: 0 8px;
  border: 0;
  border-radius: var(--kn-radius-sm);
  background: transparent;
  color: var(--ed-fg);
  font: inherit;
  font-size: var(--kn-text-sm);
  cursor: pointer;
  white-space: nowrap;
  transition: background var(--kn-dur-fast);
}
.ed-find-btn:hover { background: var(--kn-hover); }
</style>
