// src/component/editor/StatusBar.vue
<!--
  StatusBar：编辑器底部状态栏
  - 左：分支 / 诊断计数（示例数据）
  - 右：光标位置 / 选区字数 / 编码 / 语言 / 空格 / 保存状态（真实联动）
-->
<template>
  <footer class="ed-status">
    <div class="ed-status-left">
      <span class="ed-status-item">
        <Icon name="branch" :size="12" />
        main
      </span>
      <span class="ed-status-item" title="0 个错误，0 个警告">
        <i class="ed-status-dot is-error" />0
        <i class="ed-status-dot is-warn" />0
      </span>
    </div>

    <div class="ed-status-right">
      <span class="ed-status-item">Ln {{ line }}, Col {{ col }}</span>
      <span v-if="selected > 1" class="ed-status-item">{{ selected }} 个字符已选中</span>
      <span class="ed-status-item">UTF-8</span>
      <span class="ed-status-item">{{ file.language }}</span>
      <span class="ed-status-item">空格：2</span>
      <span class="ed-status-item" :title="file.modified ? '有未保存的修改' : '已保存'">
        <Icon v-if="!file.modified" name="check" :size="11" class="ed-status-saved" />
        <span v-else class="ed-status-dot is-dirty" />
        {{ file.modified ? '未保存' : '已保存' }}
      </span>
    </div>
  </footer>
</template>

<script setup lang="ts">
import { Icon } from '../common'
import type { EditorFile } from '../../data/editorFiles'

defineProps<{
  file: EditorFile
  line: number
  col: number
  /** 选中的字符数（>1 时显示） */
  selected: number
}>()
</script>

<style scoped>
.ed-status {
  height: var(--ed-status-height);
  display: flex;
  align-items: center;
  justify-content: space-between;
  padding: 0 10px;
  background: var(--ed-status-bg);
  border-top: 1px solid var(--ed-tabbar-border);
  color: var(--ed-status-fg);
  font-size: var(--kn-text-xs);
  flex-shrink: 0;
  user-select: none;
  -webkit-user-select: none;
}

.ed-status-left,
.ed-status-right {
  display: inline-flex;
  align-items: center;
  gap: 2px;
  min-width: 0;
}

.ed-status-item {
  display: inline-flex;
  align-items: center;
  gap: 4px;
  height: 18px;
  padding: 0 6px;
  border-radius: 4px;
  white-space: nowrap;
  transition: background var(--kn-dur-fast);
}
.ed-status-item:hover { background: var(--ed-status-hover); }

.ed-status-dot {
  display: inline-block;
  width: 8px;
  height: 8px;
  border-radius: 50%;
  margin: 0 1px 0 4px;
}
.ed-status-dot.is-error { background: var(--kn-rose-500); }
.ed-status-dot.is-warn  { background: var(--kn-amber-500); }
.ed-status-dot.is-dirty { background: var(--kn-amber-500); }

.ed-status-saved { color: var(--kn-emerald-500); }
</style>

// src/component/editor/StatusBar.tsx
/**
 * StatusBar：编辑器底部状态栏（React 版）
 * - 左：分支 / 诊断计数（示例）
 * - 右：光标位置 / 选区字数 / 编码 / 语言 / 保存状态（真实联动）
 */
import { Icon } from '../common/Icon'
import type { EditorFile } from '@/data/editorFiles'

export interface StatusBarProps {
  file: EditorFile
  line: number
  col: number
  selected: number
}

export function StatusBar({ file, line, col, selected }: StatusBarProps) {
  return (
    <footer className="ed-status">
      <div className="ed-status-left">
        <span className="ed-status-item">
          <Icon name="branch" size={12} />
          main
        </span>
        <span className="ed-status-item" title="0 个错误，0 个警告">
          <i className="ed-status-dot is-error" />0
          <i className="ed-status-dot is-warn" />0
        </span>
      </div>

      <div className="ed-status-right">
        <span className="ed-status-item">
          Ln {line}, Col {col}
        </span>
        {selected > 1 && <span className="ed-status-item">{selected} 个字符已选中</span>}
        <span className="ed-status-item">UTF-8</span>
        <span className="ed-status-item">{file.language}</span>
        <span className="ed-status-item">空格：2</span>
        <span className="ed-status-item" title={file.modified ? '有未保存的修改' : '已保存'}>
          {!file.modified ? (
            <Icon name="check" size={11} className="ed-status-saved" />
          ) : (
            <span className="ed-status-dot is-dirty" />
          )}
          {file.modified ? '未保存' : '已保存'}
        </span>
      </div>
    </footer>
  )
}
