// src/component/titlebar/SearchTrigger.tsx
/**
 * SearchTrigger：命令中心搜索触发器（React 版）
 * - 胶囊输入框样式 + 快捷键提示（macOS 显示 ⌘K）
 * - ⌘K / Ctrl+K 全局唤起（派发 'titlebar:search-toggle'，与 Titlebar 的开关联动）
 */
import { useEffect, useState } from 'react'
import { Icon } from '../common/Icon'
import { Kbd } from '../ui/primitives'
import { cn } from '@/lib/utils'
import { isMac } from '@/utils'

export interface SearchTriggerProps {
  open: boolean
  onOpen: () => void
}

export function SearchTrigger({ open, onOpen }: SearchTriggerProps) {
  const [focused, setFocused] = useState(false)

  useEffect(() => {
    const onKeydown = (e: KeyboardEvent) => {
      const meta = isMac ? e.metaKey : e.ctrlKey
      if (meta && e.key.toLowerCase() === 'k') {
        e.preventDefault()
        window.dispatchEvent(new CustomEvent('titlebar:search-toggle'))
      }
    }
    window.addEventListener('keydown', onKeydown)
    return () => window.removeEventListener('keydown', onKeydown)
  }, [])

  return (
    <button
      type="button"
      aria-label="打开搜索"
      onClick={onOpen}
      onMouseEnter={() => setFocused(true)}
      onMouseLeave={() => setFocused(false)}
      className={cn(
        'tb-pill tb-search-pill ui-press inline-flex h-[var(--tb-search-height)] w-[34vw] max-w-[560px] cursor-pointer items-center gap-2',
        'px-3.5 text-left text-sm text-[var(--tb-fg-muted)] transition-colors duration-200',
        (focused || open) && 'text-[var(--tb-fg)]'
      )}
      style={open ? { width: '80%' } : undefined}
    >
      <Icon name="search" size={14} className="shrink-0" />
      <span className="flex-1 truncate">搜索</span>
      <Kbd>{isMac ? '⌘ K' : 'Ctrl K'}</Kbd>
    </button>
  )
}

// src/component/titlebar/SearchTrigger.vue
<!--
  SearchTrigger：VS Code 命令中心（Command Center）风格搜索触发器
  - 静态时显示「搜索 + 快捷键」的胶囊输入框
  - 悬停 / focus 时背景与描边加深（commandCenter.active*）
  - 点击触发 openSearch
-->
<template>
  <button
    type="button"
    class="st-trigger"
    :class="{ 'is-open': modelValue }"
    :aria-label="'打开搜索'"
    @click="$emit('open')"
  >
    <Icon name="search" :size="14" class="st-icon" />
    <span class="st-text">搜索</span>
    <kbd class="st-kbd">{{ shortcutHint }}</kbd>
  </button>
</template>

<script setup lang="ts">
import { computed, onBeforeUnmount, onMounted, ref } from 'vue'
import { Icon } from '../common'

defineProps<{
  /** 搜索面板是否打开（用于切换 "is-open" 态）*/
  modelValue: boolean
}>()

defineEmits<{
  open: []
}>()

const isMac = ref(false)
const shortcutHint = computed(() => (isMac.value ? '⌘ K' : 'Ctrl K'))

onMounted(() => {
  isMac.value = /Mac|iPhone|iPad/.test(navigator.platform)
  window.addEventListener('keydown', onGlobalKeydown)
})

onBeforeUnmount(() => {
  window.removeEventListener('keydown', onGlobalKeydown)
})

/**
 * ⌘K / Ctrl+K 全局快捷键。
 * 注意：实际开关面板的逻辑由父组件持有面板状态，
 * 这里只发 open 事件；如果父组件想切换"开关"语义，
 * 可以监听此事件并 toggle 自己的 modelValue。
 */
function onGlobalKeydown(e: KeyboardEvent) {
  const meta = isMac.value ? e.metaKey : e.ctrlKey
  if (meta && e.key.toLowerCase() === 'k') {
    e.preventDefault()
    // 注意：这里不直接 emit，因为可能从关闭态触发"打开"
    // 父组件会通过监听 'open' 来 toggle
    window.dispatchEvent(new CustomEvent('titlebar:search-toggle'))
  }
}
</script>

<style scoped>
/* macOS 命令中心：22px 高、胶囊圆角、柔和凹陷底 + 描边 */
.st-trigger {
  pointer-events: auto;
  display: inline-flex;
  align-items: center;
  gap: 8px;
  height: 24px;
  padding: 0 8px 0 10px;
  background: var(--tb-search-bg);
  border: 1px solid var(--tb-search-border);
  border-radius: var(--tb-search-radius);
  color: inherit;
  font-size: var(--kn-text-sm);
  cursor: text;
  min-width: 220px;
  max-width: 600px;
  width: 34vw;
  transition:
    background var(--tb-transition-fast),
    border-color var(--tb-transition-fast),
    width var(--tb-transition-slow);
}
.st-trigger:hover {
  background: var(--tb-search-bg-hover);
  border-color: var(--tb-search-border-focus);
}
.st-trigger:focus-visible,
.st-trigger.is-open {
  background: var(--tb-search-bg-focus);
  border-color: var(--tb-search-border-focus);
  outline: none;
  width: 80%;
}

.st-icon { opacity: 0.8; }

.st-text {
  flex: 1;
  text-align: left;
  opacity: 0.7;
  white-space: nowrap;
  overflow: hidden;
  text-overflow: ellipsis;
}

.st-kbd {
  font-family: inherit;
  font-size: 10px;
  padding: 1px 5px;
  border: 1px solid var(--tb-kbd-border);
  border-radius: 3px;
  background: var(--tb-kbd-bg);
  color: var(--tb-kbd-fg);
}

/* ============ 响应式：窗口缩小时收缩搜索框 ============ */
/* 较窄：缩小宽度、隐藏快捷键 */
@media (max-width: 950px) {
  .st-trigger {
    min-width: 150px;
    width: 26vw;
  }
  .st-kbd { display: none; }
}
/* 很窄：搜索变为图标按钮 */
@media (max-width: 900px) {
  .st-trigger {
    width: 36px;
    min-width: 36px;
    max-width: 36px;
    padding: 0;
    justify-content: center;
  }
  .st-text { display: none; }
}
</style>
